25-3-19/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('night_owl.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

night_owl/urls.py
from django.urls import path
from . import views

app_name = 'night_owl'
urlpatterns = [
    path('', views.home, name="Home"),
    path('nc=<int:nc_id>/', views.nc_page, name="NC Page"),
    path('checkout/', views.checkout, name="NC Checkout"),
]

night_owl/models.py
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
    
class NC1Products(models.Model):

    #item id of each item in the menu will be its primary key
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    veg=models.BooleanField()
    currently_present=models.BooleanField()
    MY_CHOICES = ((1,'Hot and Cold Beverages'),(2,'Dosa Items'), (3, 'Sandwiches Bar'))
    filter = models.IntegerField(choices=MY_CHOICES)

    class Meta(object):
        verbose_name_plural = 'Menu items of Block 3 Night Canteen'

    def __str__(self):
        return self.name

class PaidOrdersNC1(models.Model):  # each object of this model represents a successfully created order in NC1
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ph_no = models.BigIntegerField()
    gpay_ph_no = models.BigIntegerField()
    block = models.CharField(max_length=15)
    order_comments = models.TextField(null=True, blank=True)
    MY_CHOICES = (('a','Pending'),('b','Delivered'),('c','Rejected'))
    order_details = models.TextField()
    filters = models.CharField(choices=MY_CHOICES, default='a', max_length=10)

    class Meta(object):
        verbose_name_plural = 'List of orders created - Block 3 Night Canteen'

    def __str__(self):
        return 'Order number - ' + str(self.pk)


class NC1OrderDetails(models.Model):

    order = models.ForeignKey(PaidOrdersNC1, on_delete=models.CASCADE)
    product = models.ForeignKey(NC1Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField()


class NC2Products(models.Model):

    #item id of each item in the menu will be its primary key
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    veg=models.BooleanField()
    currently_present=models.BooleanField()
    MY_CHOICES = ((1,'Hot and Cold Beverages'),(2,'Dosa Items'), (3, 'Sandwiches Bar'))
    filter = models.IntegerField(choices=MY_CHOICES)
    

    class Meta(object):
        verbose_name_plural = 'Menu items of Block 7 Night Canteen'

    def __str__(self):
        return self.name

class PaidOrdersNC2(models.Model):  # each object of this model represents a successfully created order in NC2
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ph_no = models.BigIntegerField()
    gpay_ph_no = models.BigIntegerField()
    block = models.CharField(max_length=15)
    order_comments = models.TextField(null=True, blank=True)
    MY_CHOICES = (('a','Pending'),('b','Delivered'),('c','Rejected'))
    order_details = models.TextField()
    filters = models.CharField(choices=MY_CHOICES, default='a', max_length=10)

    class Meta(object):
        verbose_name_plural = 'List of orders created - Block 7 Night Canteen'

    def __str__(self):
        return 'Order number - ' + str(self.pk)


class NC2OrderDetails(models.Model):

    order = models.ForeignKey(PaidOrdersNC2, on_delete=models.CASCADE)
    product = models.ForeignKey(NC2Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField()


class NC3Products(models.Model):
    #item id of each item in the menu will be its primary key
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    veg=models.BooleanField()
    currently_present=models.BooleanField()
    MY_CHOICES = ((1,'Noodle Items'),(2,'Rice Items'))
    filter = models.IntegerField(choices=MY_CHOICES)

    class Meta(object):
        verbose_name_plural = 'Menu items of Girl\'s Block Night Canteen'

    def __str__(self):
        return self.name

class PaidOrdersNC3(models.Model):  # each object of this model represents a successfully created order in NC3
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ph_no = models.BigIntegerField()
    gpay_ph_no = models.BigIntegerField()
    block = models.CharField(max_length=15)
    order_comments = models.TextField(null=True, blank=True)
    MY_CHOICES = (('a','Pending'),('b','Delivered'),('c','Rejected'))
    order_details = models.TextField()
    filters = models.CharField(choices=MY_CHOICES, default='a', max_length=10)

    class Meta(object):
        verbose_name_plural = 'List of orders created - Girl\'s Block Night Canteen'

    def __str__(self):
        return 'Order number - ' + str(self.pk)


class NC3OrderDetails(models.Model):

    order = models.ForeignKey(PaidOrdersNC3, on_delete=models.CASCADE)
    product = models.ForeignKey(NC3Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField()

night_owl/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

from django import forms
from .models import PaidOrdersNC1, PaidOrdersNC2, PaidOrdersNC3

class CheckoutForm(forms.Form):
    ph_no = forms.IntegerField(label="Phone Number")
    gpay_ph_no = forms.IntegerField(label="Google Pay Phone Number")
    block = forms.ChoiceField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7'), ('8', '8'),
                                       ('GH-1', 'GH-1'), ('GH-2', 'GH-2'), ('GH-3', 'GH-3'), ('GH-4', 'GH-4'), ('GH-5', 'GH-5'), 
                                       ('MT-1', 'MT-1'), ('MT-2', 'MT-2'), ('MT-3', 'MT-3'), ('MT-4', 'MT-4'),
                                       ('PG-Block', 'PG Block')], label="Block")
    order_comments = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter Order Comments (Optional)'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'post'
        
        self.helper.layout = Layout(
            'ph_no',
            'gpay_ph_no',
            'block',
            'order_comments',
            Submit('Submit', 'Submit', css_class='btn-primary')
        )

     

night_owl/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
import datetime
from django.db import connection, transaction

from night_owl.models import NC1Products, NC2Products, NC3Products, PaidOrdersNC1, PaidOrdersNC2, PaidOrdersNC3
from .forms import CheckoutForm

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def home(request):

    return render(request, "night_owl/index.html")

def nc_page(request, nc_id):
    cart = request.session.get('cart',{})

    # MySQL
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM night_owl_nc%sproducts", [nc_id])
        dishes = dictfetchall(cursor)


    if request.method == "POST":
        item_id = request.POST.get("item_id")
        qty = request.POST.get("qty")
        add = request.POST.get("add")

        # MySQL
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM night_owl_nc%sproducts WHERE id=%s", [nc_id, item_id])
            product = dictfetchall(cursor)[0]

        itemID = str(item_id)

        if (itemID not in cart) and (add == "True"):
            cart[itemID] = {
                            'NC_ID': nc_id,
                            'name': product['name'],
                            'price': product['price'],
                            'quantity': 1,
                           }

        elif (itemID not in cart) and (add == "False"):
            messages.error(request, 'This item does not exist in your cart.')

        elif (itemID in cart) and (add == "True"):
            cart[itemID]['quantity'] += 1

        elif  (itemID in cart) and (add == "False"):
            if cart[itemID]['quantity'] == 1:
                cart.pop(itemID)
            else:
                cart[itemID]['quantity'] -= 1

        request.session['cart'] = cart

        # if (cart['nc_id'] and len(cart)<3) or len(cart)<1:
        #     request.session.flush()
        #     cart = request.session.get('cart',{})

        context = {'nc_id': nc_id,
                   'cart': cart ,
                   'dishes':dishes}

        return render(request, 'night_owl/cart-table.html', context)

    context = {'nc_id': nc_id,
               'cart': cart ,
               'dishes':dishes}

    return render(request, 'night_owl/nc-page.html', context)

def checkout(request):
    if request.method == "POST":
        cart = request.session.get('cart', {})
        cart_items = {}

        if 'Submit' not in request.POST:
            nc_id = int(request.POST.get('nc_id'))

            total = 0

            for item, temp in cart.items():
                if not isinstance(temp, dict):
                    continue

                if temp['NC_ID'] == nc_id:
                    total += cart[item]['price'] * cart[item]['quantity']
                    cart_items[item] = cart[item]

            cart['nc_id'] = nc_id
            cart['total'] = total

            request.session['cart'] = cart
            form = CheckoutForm()

            context = { 'cart': cart,
                        'form': form,
                        'cart_items': cart_items }
            return render(request, 'night_owl/checkout.html', context)

        else:
            form = CheckoutForm(request.POST)
            if form.is_valid():
                nc_id = int(cart['nc_id'])
                total = int(cart['total'])
                phno = form.cleaned_data['ph_no']
                gpay_phno = form.cleaned_data['gpay_ph_no']
                block = form.cleaned_data['block']
                order_comments = form.cleaned_data['order_comments']

                if (len(str(phno)) != 10) or (len(str(gpay_phno)) != 10):
                    messages.error(request, "Please enter valid 10-digit phone numbers!")

                    for item, temp in cart.items():
                        if not isinstance(temp, dict):
                            continue

                        if temp['NC_ID'] == nc_id:
                            cart_items[item] = cart[item]

                    context = { 'cart': cart,
                        'form': form,
                        'cart_items': cart_items }

                    return render(request, 'night_owl/checkout.html', context)

                Item_id = []
                Item_name = []
                Price = []
                Quantity = []

                for item in cart:

                    if not isinstance(cart[item], dict):
                        continue

                    if cart[item]['NC_ID'] == nc_id:
                        
                        Item_id.append(int(item))
                        Item_name.append(cart[item]['name'])
                        Price.append(int(cart[item]['price']))
                        Quantity.append(int(cart[item]['quantity']))

                user_id = request.user.id
                filters = 'a'

                # MySQL
                # Wrapping the transaction in try/catch block to perform action in case 
                # of failure at any point
                try:

                    with transaction.atomic():  # Django's encapsulation of a MySQL transaction.

                        with connection.cursor() as cursor:

                            str_order_details = "Item Name - Quantity - Price Per Item\n\n"

                            for i in range (len(Item_name)):
                                str_order_details += str(Item_name[i]) + '  -  ' + str(Quantity[i]) + '  - Rs.  ' + str(Price[i]) + '\n'
                                

                            cursor.callproc ('CreatePaidOrder', [nc_id, user_id, phno, block, gpay_phno, order_comments, str_order_details, filters])
                            
                            
                            cursor.execute('''

                                SELECT LAST_INSERT_ID();

                                '''
                            )

                            order_id = cursor.fetchone()[0]
                            
                            for i in range (len (Item_name)):

                                cursor.execute('''

                                    INSERT INTO night_owl_nc%sorderdetails (order_id, product_id, quantity, total_price)
                                    VALUES (%s, %s, %s, %s);

                                    ''',  [nc_id, order_id, Item_id[i], Quantity[i], (Quantity[i] * Price[i])]
                                )

                except Exception as e:
                    return render(request, 'night_owl/failure.html', {'e': e})
                    

                request.session.flush()  # clears the cart after order has been placed.
                return render(request, 'night_owl/success.html', {'time': datetime.datetime.now()})


def view_orders (request):

    # Display all the
    if not (request.is_authenticated and request.user.is_staff):
        return HttpResponse("You don't have access to this")

    nc_id = 0

    if request.user.username == 'nc1admin':
        nc_id = 1
    if request.user.username == 'nc2admin':
        nc_id = 2
    if request.user.username == 'nc3admin':
        nc_id = 3

    # if the staff has selected a order status filter to apply
    if request.filters:

        with connection.cursor() as cursor:

            cursor.execute('''

                SELECT * FROM night_owl_paidordersnc%s WHERE filters=%s;

                ''',  [nc_id, request.filters]
            )

            data = dictfetchall(cursor)
    
    # without filters
    else:

        with connection.cursor() as cursor:

            cursor.execute('''

                SELECT * FROM night_owl_paidordersnc%s;

                ''',  [nc_id]
            
            )

            data = dictfetchall(cursor)

    return render(request, 'night_owl/staff_page.html', data)


def view_order_details (request):

    # Display all the
    if not (request.is_authenticated and request.user.is_staff):
        return HttpResponse("You don't have access to this")

    nc_id = 0

    if request.user.username == 'nc1admin':
        nc_id = 1
    if request.user.username == 'nc2admin':
        nc_id = 2
    if request.user.username == 'nc3admin':
        nc_id = 3

    with connection.cursor() as cursor:

        cursor.execute('''

            SELECT * FROM night_owl_nc%sorderdetails WHERE order_id=%s;

            ''',  [nc_id, request.order_id]
        )

        data = dictfetchall(cursor)


    return render(request, 'night_owl/order_details_page.html', data)


def edit_menu (request):

    # Display all the
    if not (request.is_authenticated and request.user.is_staff):
        return HttpResponse("You don't have access to this")

    nc_id = 0

    if request.user.username == 'nc1admin':
        nc_id = 1
    if request.user.username == 'nc2admin':
        nc_id = 2
    if request.user.username == 'nc3admin':
        nc_id = 3

    with connection.cursor() as cursor:

        cursor.execute('''

            SELECT * FROM night_owl_nc%sproducts;

            ''',  [nc_id]
        )

        data = dictfetchall(cursor)

        if request.action == 'delete':
            cursor.execute('''

                DELETE FROM night_owl_nc%sproducts WHERE id=%s;

                ''',  [nc_id, request.item_id]
            )

        elif request.action == 'update':
            cursor.execute('''

                UPDATE night_owl_nc%sproducts 
                SET name=%s, price=%s, veg=%s, currently_present=%s, filter=%s 
                WHERE id=%s;

                ''',  [nc_id, request.name, request.price, request.currently_present, request.filter, request.item_id]
            )


    return render(request, 'night_owl/edit_menu_page.html', data)

night_owl/templates/night_owl/cart-table.html
{%if cart.nc_id %}
  {%if cart.items|length > 2 %}
  <div class="cart_content">
    {% for item in cart.items%}
        {% if item.1.NC_ID == nc_id %}
          <div class="cart_row cart_row{{item.0}}">
            <div class="cart_left">
              <div class="cart_dish_name">
              {{item.1.name}}
              </div>
              <div class="cart_quantity"><span id="cart_quantity{{item.0}}">{{item.1.quantity}}</span> Nos.</div>
            </div>
            <div class="cart_right">Rs {%widthratio item.1.quantity 1 item.1.price%}</div>
          </div>
        {% endif %}
    {% endfor %}
  </div>
  <div class="submit_button">
    <form action="{% url 'night_owl:NC Checkout' %}" method="post">
      {% csrf_token %}
        <input type="hidden" id="nc_id" name="nc_id" value="{{ nc_id }}">
        <input type="submit" class="btn btn-primary" style="margin-top: 5px;" value="Checkout">
    </form>
  </div>
  {%else%}
    <div id="empty_cart"><center><i class="fa fa-shopping-cart" style="font-size:30px;"></i></center><br>Cart is empty</div>
  {%endif%}
{%elif cart.items|length > 0 %}
  <div class="cart_content">
    {% for item in cart.items%}
        {% if item.1.NC_ID == nc_id %}
          <div class="cart_row cart_row{{item.0}}">
            <div class="cart_left">
              <div class="cart_dish_name">
              {{item.1.name}}
              </div>
              <div class="cart_quantity"><span id="cart_quantity{{item.0}}">{{item.1.quantity}}</span> Nos.</div>
            </div>
            <div class="cart_right">Rs {%widthratio item.1.quantity 1 item.1.price%}</div>
          </div>
        {% endif %}
    {% endfor %}
  </div>
  <div class="submit_button">
    <form action="{% url 'night_owl:NC Checkout' %}" method="post">
      {% csrf_token %}
        <input type="hidden" id="nc_id" name="nc_id" value="{{ nc_id }}">
        <input type="submit" class="btn btn-primary" style="margin-top: 5px;" value="Checkout">
    </form>
  </div>
{%else%}
  <div id="empty_cart"><center><i class="fa fa-shopping-cart" style="font-size:30px;"></i></center><br>Cart is empty</div>
{%endif%}
  
  

night_owl/templates/night_owl/checkout.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Checkout</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'night_owl/checkout-style.css'%}">
    
</head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark"> 
    <a class="navbar-brand" href="{% url 'night_owl:Home' %}">Night Owl</a>

    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto" style="color: white;">
        <span>{{ user }}</span>
        <span><a href="/accounts/logout/" style="color: white; margin-left: 5px;">Logout</a></span>
    </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
        <a href="/accounts/login/" style="color: white;">Login</a>
    </ul>
    {% endif %}

</nav>

    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
        <div class="container">
            <h1>Checkout</h1>
        </div>
    </div>

    {% if messages %}
      <div class="alert alert-warning" style="margin-bottom: 0;">
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div> 
    {% endif %}
    
    
      
    <div class="container-fluid">
        <div class="row" style="margin-top: 10px;">
          
  
          <div class="col-md-6 order-md-2">
            <div class="card border-dark mb-3">
              <h3 class="card-header"><center>Cart Items</center></h3>
              <div class="card-body">
                <div class="container">           
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Item Name</th>
                        <th style="text-align: center;">Quantity</th>
                        <th style="text-align: center;">Total Price</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for item, key in cart_items.items %}
                        <tr>
                          {% if key.NC_ID == cart.nc_id %}
                            <td>{{ key.name }}</td>
                            <td style="text-align: center;">{{ key.quantity }}</td>
                            <td style="text-align: center;">Rs. {% widthratio key.price 1 key.quantity %}</td>
                          {% endif %}
                        </tr>
                      {% endfor %}
                    </tbody>
                    
                  </table>
                  <h5 style="text-align: center;">Order Total = Rs. {{ cart.total }}</h5>
                </div>
              </div>
            </div>
          </div>
  
          <div class="col-md-6 order-md-1">
            <div class="card border-dark mb-3">
              <h3 class="card-header"><center>Customer Details</center></h3>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="submit" id="Submit" name="Submit" class="btn btn-primary">Place Order</button>
                </form>
              </div>
            </div>
          </div>
  
        </div>
      </div>
</body>
</html>

night_owl/templates/night_owl/failure.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Checkout</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'night_owl/checkout-style.css'%}">
    
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark"> 
        <a class="navbar-brand" href="{% url 'night_owl:Home' %}">Night Owl</a>

        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto" style="color: white;">
            <span>{{ user }}</span>
            <span><a href="/accounts/logout/" style="color: white; margin-left: 5px;">Logout</a></span>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <a href="/accounts/login/" style="color: white;">Login</a>
        </ul>
        {% endif %}

    </nav>

    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
        <div class="container">
            <h1>Order Failure</h1>
        </div>
    </div>
    
    <div style="text-align: center; margin-top: 20px;">
        <h3>Your order could not be placed.</h3>
        <h5>{{ e }}</h5>
        <a href="{% url 'night_owl:Home' %}" class="btn btn-success" style="margin-top: 10px;">Back to Home Page</a>
    </div>

night_owl/templates/night_owl/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Night Owl</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'night_owl/homepage-style.css'%}">
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark"> 
        <a class="navbar-brand" href="{% url 'night_owl:Home' %}">Night Owl</a>

        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto" style="color: white;">
            <span>{{ user }}</span>
            <span><a href="/accounts/logout/" style="color: white; margin-left: 5px;">Logout</a></span>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <a href="/accounts/login/" style="color: white;">Login</a>
        </ul>
        {% endif %}

    </nav>

    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
        <div class="container">
            <h1>Night Owl</h1> 
            <p>The NITK Night Canteen App</p> 
        </div>
    </div>

    <div class="row">
        <div class="col-md-4" style="margin-top: 20px;  margin-bottom: 10px; text-align: center;">
            <div class="card" style="width: 80%; display: inline-block">
                <img class="card-img-top" src="{%static 'night_owl/fifth.jpg'%}" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h2 class="card-title">3<sup>rd</sup> Block</h2>
                    <p class="card-text">Jumadi Hospitality Pvt. Ltd.</p>
                    <a href="{% url 'night_owl:NC Page' nc_id=1 %}" class="btn btn-primary">Go to Order Page</a>
                </div>
            </div>
        </div>

        <div class="col-md-4" style="margin-top: 20px;  margin-bottom: 10px; text-align: center;">
            <div class="card" style="width: 80%; display: inline-block;">
                <img class="card-img-top" src="{%static 'night_owl/seventh.jpg'%}" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h2 class="card-title">7<sup>th</sup> Block</h2>
                    <p class="card-text">Sai Hospitality Services</p>
                    <a href="{% url 'night_owl:NC Page' nc_id=2 %}" class="btn btn-primary">Go to Order Page</a>
                </div>
            </div>
        </div>

        <div class="col-md-4" style="margin-top: 20px; margin-bottom: 10px; text-align: center;">
            <div class="card" style="width: 80%; display: inline-block">
                <img class="card-img-top" src="{%static 'night_owl/girls.jpg'%}" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h2 class="card-title">Girl's Block</h2>
                    <p class="card-text">The Sanoor Night Canteen</p>
                    <a href="{% url 'night_owl:NC Page' nc_id=3 %}" class="btn btn-primary">Go to Order Page</a>
                </div>
            </div>
        </div>
    </div>
    

</body>

night_owl/templates/night_owl/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Checkout</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'night_owl/checkout-style.css'%}">
    
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark"> 
        <a class="navbar-brand" href="{% url 'night_owl:Home' %}">Night Owl</a>
    </nav>

    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
        <div class="container">
            <h1>Order Confirmation</h1>
        </div>
    </div>
    
    <div style="text-align: center; margin-top: 20px;">
        <h3>Your order was placed successfully.</h3>
        <h5>Time of Order Placement: {{ time | time}}</h5>
        <a href="{% url 'night_owl:Home' %}" class="btn btn-success" style="margin-top: 10px;">Back to Home Page</a>
    </div>