25-3-19/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

25-3-19/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.home, name="Home"),
    path('nc=<int:nc_id>/', views.nc_page, name="NC Page"),
    path('checkout/', views.checkout, name="NC Checkout"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('night_owl.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

25-3-19/mysite/polls/models.py
from django.db import models

""" For each of the three NC's, there are two models:

    1. NC{id}Products - Contains the details of each item in the menu of that NC.

       Contains the fields - 'name' of the item
                              its 'price' in rupees
                              whether it's 'veg' or non-veg
                              whether it is 'currently_present' in the menu, and available for ordering
                             'item_type', a tuple of tuples containing all possible categories the item could belong to
                             'filters', the category to which it belongs to (i.e. one of the options present in 'item_type')

    2. PaidOrdersNC{id} - Contains the details of all the successfully placed orders, in that NC.
                          
       Contains the fields - 'ph_no' - the customer's phone number, in case they need to be contacted
                             'gpay_ph_no' - the phone number which the customer used to pay the bill amoun through Google Pay.
                                            The cashier will verify if the bill amount has been paid through this number, and 
                                            accordingly process the order.
                             'block' - The hostel block that the order should be delivered to
                             'order_comments' - any comments/suggestions about the order that the customers wish to pass on to the
                              NC staff.
                             'order_details' contains the order details, i.e., a list of all items ordered, their quantities and
                                                                                                                  total cost.
                             'order_status_values' - A tuples of tuples containing possible current order statuses (Pending, Delivered
                                                                                                             or Rejected)
                             'order_status' - A variable to store the current order status
                             
"""

class NC1Products(models.Model):

    #item id of each item in the menu will be its primary key
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    veg=models.BooleanField(default=True)
    currently_present=models.BooleanField()
    item_type = ((1,'Hot and Cold Beverages'),(2,'Dosa Items'), (3, 'Sandwiches Bar'))
    filter = models.IntegerField(choices=item_type)

    class Meta(object):
        verbose_name_plural = 'Menu items of Block 3 Night Canteen'

    def __str__(self):
        return self.name

class PaidOrdersNC1(models.Model):  # each object of this model represents a successfully created order in NC1
    ph_no = models.BigIntegerField()
    gpay_ph_no = models.BigIntegerField()
    block = models.CharField(max_length=15)
    order_comments = models.TextField(null=True, blank=True)

    order_details = models.TextField()

    order_status_values = (('a','Pending'),('b','Delivered'),('c','Rejected'))
    order_status = models.CharField(choices=order_status_values, default='a', max_length=1)

    class Meta(object):
        verbose_name_plural = 'List of orders created - Block 3 Night Canteen'

    def __str__(self):
        return 'Order number - ' + str(self.pk)

class NC2Products(models.Model):

    #item id of each item in the menu will be its primary key
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    veg=models.BooleanField(default=True)
    currently_present=models.BooleanField()
    item_type = ((1,'Hot and Cold Beverages'),(2,'Dosa Items'), (3, 'Sandwiches Bar'))
    filter = models.IntegerField(choices=item_type)
    

    class Meta(object):
        verbose_name_plural = 'Menu items of Block 7 Night Canteen'

    def __str__(self):
        return self.name

class PaidOrdersNC2(models.Model):  # each object of this model represents a successfully created order in NC2
    ph_no = models.BigIntegerField()
    gpay_ph_no = models.BigIntegerField()
    block = models.CharField(max_length=15)
    order_comments = models.TextField(null=True, blank=True)

    order_details = models.TextField()

    order_status_values = (('a','Pending'),('b','Delivered'),('c','Rejected'))
    order_status = models.CharField(choices=order_status_values, default='a', max_length=1)

    class Meta(object):
        verbose_name_plural = 'List of orders created - Block 7 Night Canteen'

    def __str__(self):
        return 'Order number - ' + str(self.pk)

class NC3Products(models.Model):
    #item id of each item in the menu will be its primary key
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    veg=models.BooleanField(default=True)
    currently_present=models.BooleanField()
    item_type = ((1,'Noodle Items'),(2,'Rice Items'))
    filter = models.IntegerField(choices=item_type)

    class Meta(object):
        verbose_name_plural = 'Menu items of Girl\'s Block Night Canteen'

    def __str__(self):
        return self.name

class PaidOrdersNC3(models.Model):  # each object of this model represents a successfully created order in NC3
    ph_no = models.BigIntegerField()
    gpay_ph_no = models.BigIntegerField()
    block = models.CharField(max_length=15)
    order_comments = models.TextField(null=True, blank=True)

    order_details = models.TextField()

    order_status_values = (('a','Pending'),('b','Delivered'),('c','Rejected'))
    order_status = models.CharField(choices=order_status_values, default='a', max_length=1)

    class Meta(object):
        verbose_name_plural = 'List of orders created - Girl\'s Block Night Canteen'

    def __str__(self):
        return 'Order number - ' + str(self.pk)

24-3-19/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
import datetime

from polls.models import NC1Products, NC2Products, NC3Products, PaidOrdersNC1, PaidOrdersNC2, PaidOrdersNC3
from .forms import CheckoutForm

def home(request):
    return render(request, "polls/index.html")

def nc_page(request, nc_id):
    cart = request.session.get('cart',{})

    if(nc_id==1):
        dishes=NC1Products.objects.all()

    elif(nc_id==2):
        dishes=NC2Products.objects.all()

    else:
        dishes=NC3Products.objects.all()

    if request.method == "POST":
        item_id = request.POST.get("item_id")
        qty = request.POST.get("qty")
        add = request.POST.get("add")

        if(nc_id==1):
            product = NC1Products.objects.get(pk=item_id)
        elif(nc_id==2):
            product = NC2Products.objects.get(pk=item_id)
        else:
            product = NC3Products.objects.get(pk=item_id)

        itemID = str(item_id)

        if (itemID not in cart) and (add == "True"):
            cart[itemID] = {
                            'NC_ID': nc_id,
                            'name': product.name,
                            'price': product.price,
                            'quantity': 1,
                           }

        elif (itemID not in cart) and (add == "False"):
            messages.error(request, 'This item does not exist in your cart.')

        elif (itemID in cart) and (add == "True"):
            cart[itemID]['quantity'] += 1

        elif  (itemID in cart) and (add == "False"):
            if cart[itemID]['quantity'] == 1:
                cart.pop(itemID)
            else:
                cart[itemID]['quantity'] -= 1

        request.session['cart'] = cart

        # if (cart['nc_id'] and len(cart)<3) or len(cart)<1:
        #     request.session.flush()
        #     cart = request.session.get('cart',{})

        context = {'nc_id': nc_id,
                   'cart': cart ,
                   'dishes':dishes}

        return render(request, 'polls/cart-table.html', context)

    context = {'nc_id': nc_id,
               'cart': cart ,
               'dishes':dishes}

    return render(request, 'polls/nc-page.html', context)

def checkout(request):
    if request.method == "POST":
        cart = request.session.get('cart', {})
        cart_items = {}

        if 'Submit' not in request.POST:
            nc_id = int(request.POST.get('nc_id'))

            total = 0

            for item, hmm in cart.items():
                if not isinstance(hmm, dict):
                    continue

                if hmm['NC_ID'] == nc_id:
                    total += cart[item]['price'] * cart[item]['quantity']
                    cart_items[item] = cart[item]

            cart['nc_id'] = nc_id
            cart['total'] = total

            request.session['cart'] = cart
            form = CheckoutForm()

            context = { 'cart': cart,
                        'form': form,
                        'cart_items': cart_items }
            return render(request, 'polls/checkout.html', context)

        else:
            form = CheckoutForm(request.POST)
            if form.is_valid():
                nc_id = int(cart['nc_id'])
                total = int(cart['total'])
                phno = form.cleaned_data['ph_no']
                gpay_phno = form.cleaned_data['gpay_ph_no']
                block = form.cleaned_data['block']
                order_comments = form.cleaned_data['order_comments']

                if (len(str(phno)) != 10) or (len(str(gpay_phno)) != 10):
                    messages.error(request, "Please enter valid 10-digit phone numbers!")

                    for item, hmm in cart.items():
                        if not isinstance(hmm, dict):
                            continue

                        if hmm['NC_ID'] == nc_id:
                            cart_items[item] = cart[item]

                    context = { 'cart': cart,
                        'form': form,
                        'cart_items': cart_items }

                    return render(request, 'polls/checkout.html', context)

                order_details = ""

                for item in cart:
                    if not isinstance(cart[item], dict):
                        continue
                    if cart[item]['NC_ID'] == nc_id:
                        order_details += cart[item]['name'] + ' - ' + str(cart[item]['quantity']) + ' - Rs. ' + str(cart[item]['price'] * cart[item]['quantity']) + '\n'


                if nc_id == 1:
                    PaidOrdersNC1.objects.create(order_details=order_details, ph_no=phno, block=block, gpay_ph_no=gpay_phno, order_comments=order_comments)
                elif nc_id == 2:
                    PaidOrdersNC2.objects.create(order_details=order_details, ph_no=phno, block=block, gpay_ph_no=gpay_phno, order_comments=order_comments)
                elif nc_id == 3:
                    PaidOrdersNC3.objects.create(order_details=order_details, ph_no=phno, block=block, gpay_ph_no=gpay_phno, order_comments=order_comments)

                request.session.flush()  # clears the cart after order has been placed.
                return render(request, 'polls/success.html', {'time': datetime.datetime.now()})

25-3-19/mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
import datetime

from polls.models import NC1Products, NC2Products, NC3Products, PaidOrdersNC1, PaidOrdersNC2, PaidOrdersNC3
from .forms import CheckoutForm

def home(request):
    return render(request, "polls/index.html")

def nc_page(request, nc_id):
    cart = request.session.get('cart',{})

    if(nc_id==1):
        dishes=NC1Products.objects.all()

    elif(nc_id==2):
        dishes=NC2Products.objects.all()

    else:
        dishes=NC3Products.objects.all()

    if request.method == "POST":  # will be true when the user tries to add/remove an item from the cart
        item_id = request.POST.get("item_id")
        qty = request.POST.get("qty")
        add = request.POST.get("add")

        if(nc_id==1):
            product = NC1Products.objects.get(pk=item_id)
        elif(nc_id==2):
            product = NC2Products.objects.get(pk=item_id)
        else:
            product = NC3Products.objects.get(pk=item_id)

        itemID = str(item_id)

        if (itemID not in cart) and (add == "True"):
            cart[itemID] = {
                            'NC_ID': nc_id,
                            'name': product.name,
                            'price': product.price,
                            'quantity': 1,
                           }

        elif (itemID not in cart) and (add == "False"):
            messages.error(request, 'This item does not exist in your cart.')

        elif (itemID in cart) and (add == "True"):
            cart[itemID]['quantity'] += 1

        elif  (itemID in cart) and (add == "False"):
            if cart[itemID]['quantity'] == 1:
                cart.pop(itemID)
            else:
                cart[itemID]['quantity'] -= 1

        request.session['cart'] = cart

        context = { 'nc_id': nc_id,
                    'cart': cart ,
                    'dishes':dishes
                  }

        return render(request, 'polls/cart-table.html', context)

    context = {
                'nc_id': nc_id,
                'cart': cart ,
                'dishes':dishes
              }
                
    return render(request, 'polls/nc-page.html', context)

def checkout(request):
    if request.method == "POST":
        cart = request.session.get('cart', {})
        cart_items = {}

        if 'Submit' not in request.POST:  # if the checkout page has been called from the nc page, not by submitting the form
            nc_id = int(request.POST.get('nc_id'))

            total = 0

            for item, temp in cart.items():  # loops through all the key-value pairs in the session dictionary
                if isinstance(temp, dict):  # checks if the value is a dictionary  
                                            # if it is, then the value is the dictonary containing the cart items

                    if temp['NC_ID'] == nc_id:  # checks if each cart item was created from the current NC, not another NC
                        total += cart[item]['price'] * cart[item]['quantity']
                        cart_items[item] = cart[item]

            cart['nc_id'] = nc_id
            cart['total'] = total

            request.session['cart'] = cart
            form = CheckoutForm()

            context = { 'cart': cart,
                        'form': form,
                        'cart_items': cart_items }
            return render(request, 'polls/checkout.html', context)

        else:
            form = CheckoutForm(request.POST)
            if form.is_valid():
                nc_id = int(cart['nc_id'])
                total = int(cart['total'])
                phno = form.cleaned_data['ph_no']
                gpay_phno = form.cleaned_data['gpay_ph_no']
                block = form.cleaned_data['block']
                order_comments = form.cleaned_data['order_comments']

                if (len(str(phno)) != 10) or (len(str(gpay_phno)) != 10):
                    messages.error(request, "Please enter valid 10-digit phone numbers!")

                    for item, temp in cart.items():
                        if isinstance(temp, dict):
                            if temp['NC_ID'] == nc_id:
                                cart_items[item] = cart[item]

                    context = { 'cart': cart,
                        'form': form,
                        'cart_items': cart_items }

                    return render(request, 'polls/checkout.html', context)

                # if all the details entered by the user in the form are valid, the following will execute:
                
                order_details = ""

                for item in cart:
                    if not isinstance(cart[item], dict):
                        continue
                    if cart[item]['NC_ID'] == nc_id:
                        order_details += cart[item]['name'] + ' - ' + str(cart[item]['quantity']) + ' - Rs. ' + str(cart[item]['price'] * cart[item]['quantity']) + '\n'


                if nc_id == 1:
                    PaidOrdersNC1.objects.create(order_details=order_details, ph_no=phno, block=block, gpay_ph_no=gpay_phno, order_comments=order_comments)
                elif nc_id == 2:
                    PaidOrdersNC2.objects.create(order_details=order_details, ph_no=phno, block=block, gpay_ph_no=gpay_phno, order_comments=order_comments)
                elif nc_id == 3:
                    PaidOrdersNC3.objects.create(order_details=order_details, ph_no=phno, block=block, gpay_ph_no=gpay_phno, order_comments=order_comments)

                request.session.flush()  # clears the cart after order has been placed.
                return render(request, 'polls/success.html', {'time': datetime.datetime.now()})
 

25-3-19/mysite/polls/templates/polls/checkout.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Checkout</title>
    <link rel="shortcut icon" href="{%static 'polls/favicon.ico'%}" type="image/x-icon" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{%static 'polls/checkout-style.css'%}">

</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'polls:Home' %}">Night Owl</a>
    </nav>

    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
        <div class="container">
            <h1>Checkout</h1>
        </div>
    </div>

    {% if messages %}
      <div class="alert alert-warning" style="margin-bottom: 0;">
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>
    {% endif %}



    <div class="container-fluid">
        <div class="row" style="margin-top: 10px;">


          <div class="col-md-6 order-md-2">
            <div class="card border-dark mb-3">
              <h3 class="card-header"><center>Cart Items</center></h3>
              <div class="card-body">
                <div class="container">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Item Name</th>
                        <th style="text-align: center;">Quantity</th>
                        <th style="text-align: center;">Total Price</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for item, key in cart_items.items %}
                        <tr>
                          {% if key.NC_ID == cart.nc_id %}
                            <td>{{ key.name }}</td>
                            <td style="text-align: center;">{{ key.quantity }}</td>
                            <td style="text-align: center;">Rs. {% widthratio key.price 1 key.quantity %}</td>
                          {% endif %}
                        </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                  <h5 style="text-align: center;">Order Total = Rs. {{ cart.total }}</h5>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 order-md-1">
            <div class="card border-dark mb-3">
              <h3 class="card-header"><center>Customer Details</center></h3>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="submit" id="Submit" name="Submit" class="btn btn-primary">Place Order</button>
                </form>
              </div>
            </div>
          </div>

        </div>
      </div>
</body>
</html>

25-3-19/mysite/polls/templates/polls/nc-page.html
{% load static %}
{% load extras %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Canteen Name</title>
  <link rel="shortcut icon" href="{%static 'polls/favicon.ico'%}" type="image/x-icon" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Linking the icon library used for the hamburger menu -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <link rel="stylesheet" type="text/css" href="{%static 'polls/main-style.css'%}">

  <!-- Optional JS Stuff -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="//raw.github.com/botmonster/jquery-bootpag/master/lib/jquery.bootpag.min.js"></script>


<script>
  var box_id, item_name, item_price, search_value,a, b, element_id, nc_id;
  function add_to_cart(box_id, item_name, item_price){
    document.querySelector("#add_or_remove"+ box_id).style.display="inline-block";
    document.querySelector("#quantity" + box_id).innerHTML=1;
    document.querySelector("#cart_form_type2"+box_id).style.display="none";
  }

    /* for incrementing/decrementing item quantity */
  function increaseValue(box_id) {
    var value = parseInt(document.querySelector('#quantity'+box_id).innerText);
    value++;
    document.querySelector('#quantity'+box_id).innerText = value;
  }

  function decreaseValue(box_id) {
    var value = parseInt(document.querySelector('#quantity'+box_id).innerText);
    value--;
    if(value<1)
      {
         document.querySelector("#add_or_remove"+ box_id).style.display="none";
         document.querySelector("#cart_form_type2"+box_id).style.display="block";
      }
    else{
        document.querySelector('#quantity'+box_id).innerText = value;
    }
  }

  function search_bar(search_value){
       boxes=document.querySelectorAll(".item_box .item_name");
       for(var j=0;j<boxes.length;j++){
              document.querySelectorAll(".item_outerbox")[j].style.display="block";
       }
       for(var j=0;j<boxes.length;j++){
          if(!boxes[j].innerHTML.toLowerCase().includes(search_value.toLowerCase())){
               document.querySelectorAll(".item_outerbox")[j].style.display="none";
          }
       }
  }
  function removeElement(a,b)
    {
         if(a==1)
            {document.querySelector(".row"+b).style.display= "none";
             document.querySelector(".ext"+ b+" "+".down").style.display="inline-block";
             document.querySelector(".ext"+ b+" "+"      .up").style.display="none";
            }
         else
             {document.querySelector(".row"+b).style.display= "flex";
              document.querySelector(".ext"+ b+" "+".up").style.display="inline-block";
              document.querySelector(".ext"+ b+" "+"      .down").style.display="none";
            }
   }

<!-- Sends a POST request through AJAX when an item is added to cart(with jQuery) -->
  $(function() {
    $(".cart_form, .cart_form_type2").submit(function(event) {
        // Stop form from submitting normally
        event.preventDefault();
        var friendForm = $(this);
        // Send the data using post
        var posting = $.post( friendForm.attr('action'), friendForm.serialize() );
        // if success:
        posting.done(function(data) {

            $('.cart-table').html(data);

            // success actions, maybe change submit button to 'friend added' or whatever
        });
        // if failure:
        posting.fail(function(data) {
            // 4xx or 5xx response, alert user about failure
        });
      });
    });
</script>
</head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'polls:Home' %}">Night Owl</a>
  </nav>

  {% if nc_id == 1 %}
  <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
    <div class="container">
        <h1>Jumadi Hospitality Pvt. Ltd. - Block 3</h1>
        <p>Contact - <a>9380807887</a>, <a>9972209930</a></p>
    </div>
  </div>
  {% elif nc_id == 2 %}
  <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
    <div class="container">
        <h1>Sai Hospitality Services - Block 7</h1>
        <p>Contact - <a>9380802849</a>, <a>9972209920</a></p>
    </div>
  </div>
  {% elif nc_id == 3 %}
    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
      <div class="container">
          <h1>The Sanoor Canteen</h1>
          <p>Contact - <a>9380948425</a>, <a>9632841017</a></p>
      </div>
    </div>
  {% endif %}

{% if messages %}
<ul class="messages">
  {% for message in messages %}
    <li class="{{ message.tags }}">{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
<div class="row row_content">

    <div class="content col-sm-12 col-md-8">
    <input id="searchbar" type="text" class="search" placeholder="Search here" oninput="search_bar(this.value)">
          {%sort_by_filter dishes as groupedbyfilters%}
          {%for bar in groupedbyfilters%}
          <div class="FilterName">
              {{bar.0.get_filter_display}}
              <span class="menuExtension ext{{forloop.counter}}"><button class="up" onclick="removeElement(1,'{{forloop.counter}}')"><i class="fa fa-chevron-up"></i></button>
              <button class="down" onclick="removeElement(0,'{{forloop.counter}}')">
              <i class="fa fa-chevron-down" ></i></button>
              </span>
          </div>
          <div class="row row{{forloop.counter}}">
          {%for item in bar|sort_by_price %}
          {%if item.currently_present%}
          <div class="col-sm-12 col-md-6 item_outerbox">
            <div class="item_box" id="item_box{{item.id}}">
              {%if item.veg == True%}
                <img class="veg" src="{%static 'polls/veg.jpg'%}">
              {%else%}
                <img class="veg" src="{%static 'polls/non-veg.png'%}">
              {%endif%}
              <span class="item_name">{{item.name}}</span><br>
              <span class="item_cost">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rs {{item.price}}</span><br>



              <div class="add_or_remove" id="add_or_remove{{item.id}}" style="
                {%if item.id|tostring not in cart%}
                display: none;
                {%endif%}"
              >
                <form action="{% url 'polls:NC Page' nc_id=nc_id %}" class="cart_form" method="post">
                  {% csrf_token %}
                    <input type="hidden" id="item_id" name="item_id" value="{{ item.id }}">
                    <input type="hidden" id="add" name="add" value="False">
                    <input type="submit" value="-" onclick="decreaseValue({{item.id}})">
                </form>
                <span id="quantity{{item.id}}">
                  {%for ite in cart.items %}
                    {% if ite.1.NC_ID == nc_id %}
                      {%if ite.0 == item.id|tostring %}
                        {{ite.1.quantity}}
                      {%endif%}
                    {%endif%}
                  {%endfor%}
                  </span>
                  <form action="{% url 'polls:NC Page' nc_id=nc_id %}" class="cart_form" method="post">
                    {% csrf_token %}
                      <input type="hidden" id="item_id" name="item_id" value="{{ item.id }}">
                      <input type="hidden" id="add" name="add" value="True">
                      <input type="submit" value="+" onclick="increaseValue({{item.id}})">
                  </form>
              </div>
                <form class="cart_form_type2"  id="cart_form_type2{{item.id}}"  action="{% url 'polls:NC Page' nc_id=nc_id %}" method="post" style="
                {%if item.id|tostring in cart%}
                  display: none;
                {%endif%}"
                >
                  {% csrf_token %}
                    <input type="hidden" id="item_id" name="item_id" value="{{ item.id }}">
                    <input type="hidden" id="add" name="add" value="True">
                    <input id="add{{item.id}}" class="cart_form_input" type="submit" value="Add" onclick="add_to_cart({{item.id}}, '{{item.name}}', {{item.price}})">
                </form>
            </div>
          </div>
          {%endif%}
        {%endfor%}
        </div>
        {%endfor%}
    </div>
    <div class="col-sm-12 col-md-4" id="cart_box">
      <div style="font-size:16px;background-color: green;color: white;padding:7px;height: 40px;">
          <center>Cart</center>
      </div>
      <div class="cart-table">
        {%include 'polls/cart-table.html'%}
      </div>
    </div>
    <div id="cart_box_link" style="width:100%;padding:10px 5%;;background-color:white;position: fixed;bottom:0px;z-index:3;">
      <div class="col-sm-12 col-md-0" style="font-size:16px;background-color: green;color: white;padding:7px;height: 40px;">
        <a href="#cart_box" style="color:white;"><center>Cart</center> </a>
      </div>
    </div>

</html>

25-3-19/mysite/polls/templates/polls/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Checkout</title>
    <link rel="shortcut icon" href="{%static 'polls/favicon.ico'%}" type="image/x-icon" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{%static 'polls/checkout-style.css'%}">

</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'polls:Home' %}">Night Owl</a>
    </nav>

    <div class="jumbotron jumbotron-fluid text-center">  <!-- BootStrap's jumbotron class for big titles-->
        <div class="container">
            <h1>Order Confirmation</h1>
        </div>
    </div>

    <div style="text-align: center; margin-top: 20px;">
        <h3>Your order was placed successfully.</h3>
        <h5>Time of Order Placement: {{ time | time}}</h5>
        <a href="{% url 'polls:Home' %}" class="btn btn-success" style="margin-top: 10px;">Back to Home Page</a>
    </div>